# Generated by Django 4.1.7 on 2023-04-11 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addstudent',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='forapp.addcourse'),
        ),
    ]
